### ISSUE TITLE
What is the difference between "when block" and "when argument"?

### ISSUE THREAD

**Issue by ynigun** [wesovilabs/orion#11]
I'm trying to wrap my head around the syntax
It's a bit confusing to have both a [block](https://github.com/ivancorrales/orion-test-maths/blob/97c812b6a604d2e90da2cfb28c1b9a99c67db629/scenario-mult.hcl#L14) and a [argument](https://github.com/ivancorrales/orion-test-maths/blob/97c812b6a604d2e90da2cfb28c1b9a99c67db629/scenario-mult.hcl#L23) with the name "when".
Is it used for a similar action?
Because it seems that the "when" block is not used as a condition for a scenario.

**Comment by ivancorrales** [comment]
The   `block when`   is used to define the set of actions under the test.   On the other hand, the `argument when` in the actions permits us to define conditional actions. It means, argument when is used to describe alternative flows in a scenario.
